Preparação do OpenDSS

In [2]:
import pandas as pd
import py_dss_interface
from py_dss_toolkit import dss_tools

dss_file = r"C:\Dados_teste\OpenDSS\GWO\Alim_Meia_Ponte_5_REDUZIDO\Master_PyDSS_Interface.dss"

dss = py_dss_interface.DSS()

dss_tools.update_dss(dss)

dss.text(f"compile [{dss_file}]")
dss.text("buscoords buscoords.csv")

def decide_element(bus: str, buses_df: pd.DataFrame, trafo_df: pd.DataFrame, lines_df: pd.DataFrame):
    bus = bus.split(".")[0]
    elements_query = buses_df.query(f"name == '{bus}'")["all_pde_active_bus"].iloc[0]

    distance = 1e6
    for element in elements_query:
        element_type, element_name = element.split(".")

        if element_type == "Line":
            segment_df = lines_df.query(f"name == '{element_name}'")

            element_bus = segment_df["bus_name"].iloc[0]
            distance_bus = buses_df.query(f"name == '{element_bus}'")["distance"].iloc[0]

            if "mt" in element_name:
                kv = 13.8

            elif "bt" in element_name:
                kv = 0.38

            else:
                continue

        elif element_type == "Transformer":
            element_bus = trafo_df.query(f"name == '{element_name}'")["bus_name"].iloc[0]
            distance_bus = buses_df.query(f"name == '{element_bus}'")["distance"].iloc[0]
            kv = trafo_df.query(f"name == '{element_name}'")["kv"].iloc[0]

        else:
            continue

        if distance_bus < distance:
            distance = distance_bus
            selected_element = element_name
            selected_element_type = element_type
            selected_kv = kv

    return selected_element_type, selected_element, selected_kv

def calc_rpf() -> float:
    soma = 0
    for name in dss.monitors.names:
        if "voltage" in name:
            continue

        if "battery" in name:
            continue

        dss.monitors.name = name
        monitor = dss.monitors.channel(1)

        soma += sum(x for x in monitor if x < 0)

    return soma

buses_df = dss_tools.model.buses_df
trafo_df = dss_tools.model.transformers_df
lines_df = dss_tools.model.lines_df

trafo_df["bus_name"] = trafo_df["bus"].str.split(".").str[0]
lines_df["bus_name"] = lines_df["bus1"].str.split(".").str[0]

buses_df = buses_df[["name", "distance", "all_pce_active_bus", "all_pde_active_bus"]]

In [22]:
import py_dss_interface
from py_dss_toolkit import dss_tools
from matplotlib import pyplot as plt

solution_buses = ['95217345002086b', '94336115002086b', '81489125002086', '82021615286802', '82025745286821']
#solution_buses = ['95217345002086b', '81489125002086', '82021615286802', '82025745286821']

dss_file = r"C:\Dados_teste\OpenDSS\GWO\Alim_Meia_Ponte_5_REDUZIDO\Master_PyDSS_Interface.dss"

dss = py_dss_interface.DSS()

dss_tools.update_dss(dss)

df_rpf = pd.DataFrame(columns=["Caso", "Fluxo Reverso Total (kWh)"])

voltage_dfs_base_case = {}

cases = ["Caso Base", "Caso Ótimo"]

for case in cases:

    dss.text(f"compile [{dss_file}]")

    dss.text("Redirect 'PV_System_120_MeiaPonte.dss'")
    #dss.text("Redirect 'PVSystem_120_Irrad.dss")
    dss.text("buscoords buscoords.csv")

    if case == "Caso Ótimo":

        for i, bus in enumerate(solution_buses):
            element_type, element_name, kv = decide_element(bus, buses_df, trafo_df, lines_df)
            pot = 280

            dss.text(f"New Storage.Battery_{i} phases=3 bus1={bus} kv={kv} kWrated={pot} kWhrated={8*pot} dispmode=follow %stored=50")
            
            dss.text(f"New StorageController.SC_{i} element={element_type}.{element_name} terminal=1 modedis=peakShave elementList=[Battery_{i}]\n"
            f"~ MonPhase=AVG kwtarget=5 modecharge=peakShaveLow kwtargetLow=0\n\n")

            dss.text(f"New Monitor.Battery_{i} element=Storage.Battery_{i} mode=7")

    dss.text(f"buscoords BusCoords.csv")

    dss.text("set mode=daily")
    dss.text("set stepsize=1h")
    dss.text("set number=24")

    dss.solution.solve()

    energymeter_df = dss_tools.results.energymeters

    if case == "Caso Base":
        for name in dss.monitors.names:
            if not "voltage" in name:
                continue

            voltage_dfs_base_case[name] = dss_tools.results.monitor(name)

    elem_1, elem_2, elem_3, elem_4, elem_5 = "trf_5286812a", "trf_5552819a", "trf_5286964a", "trf_5286821a", "trf_5286934a"

    if case == "Caso Ótimo":
        df_optimal_feeder = dss_tools.results.monitor("feeder")
        df_optimal_trafo_1 = dss_tools.results.monitor(elem_1)
        df_optimal_trafo_2 = dss_tools.results.monitor(elem_2)
        df_optimal_trafo_3 = dss_tools.results.monitor(elem_3)
        df_optimal_trafo_4 = dss_tools.results.monitor(elem_4)
        df_optimal_trafo_5 = dss_tools.results.monitor(elem_5)

    elif case == "Caso Base":
        df_base_feeder = dss_tools.results.monitor("feeder")
        df_base_trafo_1 = dss_tools.results.monitor(elem_1)
        df_base_trafo_2 = dss_tools.results.monitor(elem_2)
        df_base_trafo_3  = dss_tools.results.monitor(elem_3)
        df_base_trafo_4  = dss_tools.results.monitor(elem_4)
        df_base_trafo_5  = dss_tools.results.monitor(elem_5)

    print(f"{case}")
    display(energymeter_df[["kwh", "kvarh", "zone kwh", "zone losses kwh"]])

    rpf = calc_rpf()
    df2 = pd.DataFrame({"Caso": [case], "Fluxo Reverso Total (kWh)": [rpf]})

    df_rpf = pd.concat([df_rpf, df2], ignore_index=True)

#Fluxo reverso total
display(df_rpf)

Caso Base

            kwh         kvarh       zone kwh  zone losses kwh
0  49444.317416  65469.605055  120501.062097      5882.456263

Caso Ótimo

            kwh         kvarh       zone kwh  zone losses kwh
0  48330.814782  64691.205533  120571.610121      5528.233247

         Caso Fluxo Reverso Total (kWh)
0   Caso Base             -23302.206599
1  Caso Ótimo             -21253.003351

Elementos nas barras problemáticas

In [44]:
buses_df = dss_tools.model.buses_df
solution_buses_fixed = []

for bus in solution_buses:
    solution_buses_fixed.append(bus.split(".")[0])

display(buses_df.query(f"name in {solution_buses_fixed}"))

,name,nodes,num_nodes,kv_base,distance,coord_defined,x,y,latitude,longitude,all_pce_active_bus,all_pde_active_bus,line_list,line_total_miles,load_list,section_id,total_customers
114,95217345002086b,"[1, 2, 3]",3,7.967434,3.917069,1,-49.318135,-16.602941,0.0,0.0,[Storage.battery_0],"[Line.cmt_5722432, Line.smt_55281851]","[LINE.cmt_5722432, LINE.smt_55281851]",0.0,[None],0,0
354,82033655002086,"[1, 2, 3]",3,7.967434,8.060878,1,-49.330809,-16.616380,0.0,0.0,[Storage.battery_1],[Line.smt_53072692],[LINE.smt_53072692],0.0,[None],0,0
1006,81489125002086,"[1, 2, 3]",3,7.967434,1.253358,1,-49.324749,-16.586983,0.0,0.0,[Storage.battery_2],"[Line.smt_53074008, Line.smt_53074009]","[LINE.smt_53074008, LINE.smt_53074009]",0.0,[None],0,0
1093,82021615286802,"[1, 2, 3, 4]",4,0.219393,4.759274,1,-49.311880,-16.604551,0.0,0.0,"[Load.m2_trf_5286802a, Load.m1_trf_5286802a, R...",[Transformer.trf_5286802a],[None],0.0,"[LOAD.m2_trf_5286802a, LOAD.m1_trf_5286802a]",0,0
1112,82025745286821,"[1, 2, 3, 4]",4,0.219393,8.165772,1,-49.330934,-16.628300,0.0,0.0,"[Load.m2_trf_5286821a, Load.m1_trf_5286821a, R...",[Transformer.trf_5286821a],[None],0.0,"[LOAD.m2_trf_5286821a, LOAD.m1_trf_5286821a]",0,0

Mapa com os barramentos

In [6]:
colors = ["red", "blue", "green", "purple", "yellow"]
bus_list = []
for i, bus in enumerate(solution_buses):
    bus_list.append(dss_tools.interactive_view.circuit_get_bus_marker(name=bus, color=colors[i], size=10)) 

#bus_list = [dss_tools.interactive_view.circuit_get_bus_marker(name=solution_buses[3], color=colors[3], size=10)]

print(bus_list)

dss_tools.interactive_view.circuit_geoplot(parameter="active power", title="Circuit Plot with Solution Buses", show=True, bus_markers=bus_list)

[CircuitBusMarker(name='95217345002086b', symbol='square', size=10, color='red', marker_name='95217345002086b'), CircuitBusMarker(name='82033655002086', symbol='square', size=10, color='blue', marker_name='82033655002086'), CircuitBusMarker(name='81489125002086', symbol='square', size=10, color='green', marker_name='81489125002086'), CircuitBusMarker(name='82021615286802', symbol='square', size=10, color='purple', marker_name='82021615286802'), CircuitBusMarker(name='82025745286821', symbol='square', size=10, color='yellow', marker_name='82025745286821')]

In [36]:
buses_df = dss_tools.model.buses_df
trafo_df = dss_tools.model.transformers_df
lines_df = dss_tools.model.lines_df

trafo_df["buses"] = trafo_df["buses"].apply(
    lambda x: [bus.strip() for bus in x.strip("[]").split(",") if bus.strip()]
)

bus_list = []
bus_in_loads = []
bus_graph = []

for bus in solution_buses:
    query_df = buses_df.query(f"name == '{bus}'")[["all_pce_active_bus", "all_pde_active_bus"]]
    pce_elements = query_df["all_pce_active_bus"].iloc[0]

    if "load" in pce_elements[0].lower():
        bus_in_loads.append(bus)
        pde_elements = query_df["all_pde_active_bus"].iloc[0]
        pde_element = pde_elements[0].split(".")[1]

        if "trf_" in pde_element.lower():
            buses = trafo_df.query(f"name == '{pde_element}'")["buses"].iloc[0]
            bus1 = buses[0]
            bus1 = bus1.split(".")[0]
            print(bus1)
            bus_graph.append(bus1)

        else:
            bus1 = lines_df.query(f"name == '{pde_element}'")["bus"].iloc[0]
            bus_graph.append(bus1)

for i, bus in enumerate(bus_graph):
    bus_list.append(dss_tools.interactive_view.circuit_get_bus_marker(name=bus, color=colors[i], size=10)) 

print(bus_list)

dss_tools.interactive_view.circuit_geoplot(parameter="active power", title="Circuit Plot with Solution Buses", show=True, bus_markers=bus_list)

82021615002086
82025745002086
[CircuitBusMarker(name='82021615002086', symbol='square', size=10, color='red', marker_name='82021615002086'), CircuitBusMarker(name='82025745002086', symbol='square', size=10, color='blue', marker_name='82025745002086')]

Barras ilhadas (só um elemento PDE conectado)

In [ ]:
print(type(buses_df["all_pce_active_bus"].iloc[1][0]))
print(type(buses_df["all_pde_active_bus"].iloc[1]))

isolated_buses = []

for _, row in buses_df.iterrows():
    if row["all_pce_active_bus"][0] == "None" and len(row["all_pde_active_bus"]) < 2:
        isolated_buses.append(row["name"])

print(isolated_buses)
print(len(isolated_buses))

#for bus in isolated_buses:
#    display(buses_df.query(f"name == '{bus}'"))

<class 'str'>
<class 'list'>
['i888888340825002086b', '82021905002086', '82031435002086', '82036215002086', '82032955002086', '82033655002086', '82032275002086', '82049135002086', '82050245002086', '82049695002086', '82040095002086', '82049745002086', '82049895002086', '82049925002086', '82040735002086', '82065615002086', '82039665002086', '82042055002086', '88685565002086', '88686185002086', '94074915002086b', '94074915002086', '94125525002086b', '94128575002086b', '94511165002086b', '94511165002086', '94522045002086', '94531885002086b', '94531885002086', '94324465002086b', '94324465002086', '94329955002086', '94329955002086b', '94335985002086', '94335985002086b', '94336115002086', '94336115002086b', '94660965002086', '94661005002086', '90349985002086', '95170945002086b', '95170975002086b', '95200805002086b', '95200805002086', '95217195002086', '95217195002086b', '95224855002086', '95225005002086', '94563035002086b', '94563035002086', '95242395002086', '95244945002086', '94777925002086b', '94777925002086', '95404055002086b', '95404055002086', '89895775002086b', '95423925002086', '82025135002086', '91881405002086', '82051715002086b', '96582725002086', '91881405002086b', '88185375002086', '82049605002086', '91879905002086b', '93304335002086b', '81463935002086', 'i888888467345002086', 'i888888340595002086', '93304305002086', '82032055002086', '81480555002086b', '96957955002086b', 'i888888516525002086g', 'int157715002086', 'i888888516585002086']
77

                     name  distance all_pce_active_bus    all_pde_active_bus
128  i888888340825002086b       0.0             [None]  [Line.cmt_sa0002751]

               name  distance all_pce_active_bus   all_pde_active_bus
134  82021905002086  3.916473             [None]  [Line.smt_53072476]

               name  distance all_pce_active_bus   all_pde_active_bus
291  82031435002086  7.005301             [None]  [Line.smt_53072627]

               name  distance all_pce_active_bus   all_pde_active_bus
302  82036215002086  6.082723             [None]  [Line.smt_53072638]

               name  distance all_pce_active_bus   all_pde_active_bus
303  82032955002086  7.355117             [None]  [Line.smt_53072639]

               name  distance all_pce_active_bus   all_pde_active_bus
354  82033655002086  8.060878             [None]  [Line.smt_53072692]

               name  distance all_pce_active_bus   all_pde_active_bus
503  82032275002086  6.745213             [None]  [Line.smt_53073126]

               name  distance all_pce_active_bus   all_pde_active_bus
525  82049135002086  7.743263             [None]  [Line.smt_53073151]

               name  distance all_pce_active_bus   all_pde_active_bus
539  82050245002086  7.994105             [None]  [Line.smt_53073163]

               name  distance all_pce_active_bus   all_pde_active_bus
546  82049695002086  8.307447             [None]  [Line.smt_53073168]

               name  distance all_pce_active_bus   all_pde_active_bus
570  82040095002086  8.593786             [None]  [Line.smt_53073216]

               name  distance all_pce_active_bus   all_pde_active_bus
579  82049745002086  8.427812             [None]  [Line.smt_53073227]

               name  distance all_pce_active_bus   all_pde_active_bus
596  82049895002086  7.773044             [None]  [Line.smt_53073247]

               name  distance all_pce_active_bus   all_pde_active_bus
597  82049925002086  8.433414             [None]  [Line.smt_53073248]

               name  distance all_pce_active_bus   all_pde_active_bus
649  82040735002086  9.074628             [None]  [Line.smt_53073325]

               name  distance all_pce_active_bus   all_pde_active_bus
678  82065615002086  8.161951             [None]  [Line.smt_53073426]

               name  distance all_pce_active_bus   all_pde_active_bus
781  82039665002086  5.835254             [None]  [Line.smt_53073746]

               name  distance all_pce_active_bus   all_pde_active_bus
784  82042055002086  5.836987             [None]  [Line.smt_53073749]

               name  distance all_pce_active_bus   all_pde_active_bus
826  88685565002086   5.12914             [None]  [Line.smt_54442294]

               name  distance all_pce_active_bus   all_pde_active_bus
831  88686185002086  5.007159             [None]  [Line.smt_54442470]

                name  distance all_pce_active_bus   all_pde_active_bus
836  94074915002086b  7.849702             [None]  [Line.smt_55136032]

               name  distance all_pce_active_bus   all_pde_active_bus
838  94074915002086  7.817016             [None]  [Line.smt_55136055]

                name  distance all_pce_active_bus   all_pde_active_bus
840  94125525002086b  7.013509             [None]  [Line.smt_55141988]

                name  distance all_pce_active_bus   all_pde_active_bus
842  94128575002086b  7.028886             [None]  [Line.smt_55142003]

                name  distance all_pce_active_bus   all_pde_active_bus
853  94511165002086b  4.743101             [None]  [Line.smt_55194722]

               name  distance all_pce_active_bus   all_pde_active_bus
855  94511165002086  4.707465             [None]  [Line.smt_55194725]

               name  distance all_pce_active_bus   all_pde_active_bus
856  94522045002086  5.202633             [None]  [Line.smt_55196380]

                name  distance all_pce_active_bus   all_pde_active_bus
859  94531885002086b  3.988502             [None]  [Line.smt_55198003]

               name  distance all_pce_active_bus   all_pde_active_bus
860  94531885002086  3.951882             [None]  [Line.smt_55198004]

                name  distance all_pce_active_bus   all_pde_active_bus
866  94324465002086b   7.01458             [None]  [Line.smt_55168308]

               name  distance all_pce_active_bus   all_pde_active_bus
868  94324465002086  6.995458             [None]  [Line.smt_55168309]

               name  distance all_pce_active_bus   all_pde_active_bus
870  94329955002086  5.636361             [None]  [Line.smt_55168956]

                name  distance all_pce_active_bus   all_pde_active_bus
872  94329955002086b  5.636381             [None]  [Line.smt_55168957]

               name  distance all_pce_active_bus   all_pde_active_bus
875  94335985002086  5.235469             [None]  [Line.smt_55169884]

                name  distance all_pce_active_bus   all_pde_active_bus
877  94335985002086b  5.272641             [None]  [Line.smt_55169885]

               name  distance all_pce_active_bus   all_pde_active_bus
879  94336115002086  7.818894             [None]  [Line.smt_55169910]

                name  distance all_pce_active_bus   all_pde_active_bus
881  94336115002086b  7.817528             [None]  [Line.smt_55169918]

               name  distance all_pce_active_bus   all_pde_active_bus
883  94660965002086  8.176794             [None]  [Line.smt_55216503]

               name  distance all_pce_active_bus   all_pde_active_bus
884  94661005002086  8.177883             [None]  [Line.smt_55216509]

               name  distance all_pce_active_bus   all_pde_active_bus
887  90349985002086  3.382339             [None]  [Line.smt_54662605]

                name  distance all_pce_active_bus   all_pde_active_bus
891  95170945002086b  8.932635             [None]  [Line.smt_55275126]

                name  distance all_pce_active_bus   all_pde_active_bus
895  95170975002086b  8.949009             [None]  [Line.smt_55275144]

                name  distance all_pce_active_bus   all_pde_active_bus
897  95200805002086b  6.578529             [None]  [Line.smt_55279570]

               name  distance all_pce_active_bus   all_pde_active_bus
900  95200805002086  6.531504             [None]  [Line.smt_55279583]

               name  distance all_pce_active_bus   all_pde_active_bus
902  95217195002086   3.91294             [None]  [Line.smt_55281832]

                name  distance all_pce_active_bus   all_pde_active_bus
904  95217195002086b  3.958353             [None]  [Line.smt_55281833]

               name  distance all_pce_active_bus   all_pde_active_bus
913  95224855002086  9.443877             [None]  [Line.smt_55282953]

               name  distance all_pce_active_bus   all_pde_active_bus
914  95225005002086  9.441386             [None]  [Line.smt_55282974]

                name  distance all_pce_active_bus   all_pde_active_bus
921  94563035002086b  7.145018             [None]  [Line.smt_55203302]

               name  distance all_pce_active_bus   all_pde_active_bus
923  94563035002086  7.109957             [None]  [Line.smt_55203305]

               name  distance all_pce_active_bus   all_pde_active_bus
925  95242395002086  6.929586             [None]  [Line.smt_55285517]

               name  distance all_pce_active_bus   all_pde_active_bus
926  95244945002086  4.665703             [None]  [Line.smt_55285839]

                name  distance all_pce_active_bus   all_pde_active_bus
929  94777925002086b  5.381273             [None]  [Line.smt_55231652]

               name  distance all_pce_active_bus   all_pde_active_bus
931  94777925002086  5.350227             [None]  [Line.smt_55231664]

                name  distance all_pce_active_bus   all_pde_active_bus
950  95404055002086b  7.654952             [None]  [Line.smt_55303781]

               name  distance all_pce_active_bus   all_pde_active_bus
951  95404055002086  7.617383             [None]  [Line.smt_55303782]

                name  distance all_pce_active_bus   all_pde_active_bus
954  89895775002086b  5.602252             [None]  [Line.smt_55306588]

               name  distance all_pce_active_bus   all_pde_active_bus
956  95423925002086  5.610073             [None]  [Line.smt_55306592]

               name  distance all_pce_active_bus   all_pde_active_bus
974  82025135002086  8.769474             [None]  [Line.smt_55365181]

                name  distance all_pce_active_bus   all_pde_active_bus
1030  91881405002086  4.388971             [None]  [Line.smt_54759971]

                 name  distance all_pce_active_bus   all_pde_active_bus
1033  82051715002086b  6.190997             [None]  [Line.smt_55449279]

                name  distance all_pce_active_bus   all_pde_active_bus
1035  96582725002086  6.205529             [None]  [Line.smt_55449287]

                 name  distance all_pce_active_bus   all_pde_active_bus
1036  91881405002086b  4.360286             [None]  [Line.smt_54852370]

                name  distance all_pce_active_bus   all_pde_active_bus
1037  88185375002086  8.871072             [None]  [Line.smt_54377218]

                name  distance all_pce_active_bus   all_pde_active_bus
1041  82049605002086  7.491084             [None]  [Line.smt_54366717]

                 name  distance all_pce_active_bus   all_pde_active_bus
1044  91879905002086b  4.457741             [None]  [Line.smt_55036091]

                 name  distance all_pce_active_bus   all_pde_active_bus
1047  93304335002086b  5.288273             [None]  [Line.smt_55036162]

                name  distance all_pce_active_bus   all_pde_active_bus
1048  81463935002086  4.443905             [None]  [Line.smt_55052959]

                     name  distance all_pce_active_bus      all_pde_active_bus
1050  i888888467345002086       0.0             [None]  [Line.smt_88888862056]

                     name  distance all_pce_active_bus      all_pde_active_bus
1052  i888888340595002086       0.0             [None]  [Line.smt_88888843883]

                name  distance all_pce_active_bus   all_pde_active_bus
1053  93304305002086  5.273661             [None]  [Line.smt_55035231]

                name  distance all_pce_active_bus   all_pde_active_bus
1054  82032055002086  7.863823             [None]  [Line.smt_54314575]

                 name  distance all_pce_active_bus   all_pde_active_bus
1063  81480555002086b  8.819677             [None]  [Line.smt_55501923]

                 name  distance all_pce_active_bus   all_pde_active_bus
1066  96957955002086b  8.832597             [None]  [Line.smt_55501929]

,name,distance,all_pce_active_bus,all_pde_active_bus
1068,i888888516525002086g,0.0,[None],[Line.smt_88888869150]

                 name  distance all_pce_active_bus      all_pde_active_bus
1070  int157715002086       0.0             [None]  [Line.smt_88888869156]

                     name  distance all_pce_active_bus      all_pde_active_bus
1071  i888888516585002086       0.0             [None]  [Line.smt_88888869158]

In [21]:
bus_list = []
for i, bus in enumerate(isolated_buses):
    bus_list.append(dss_tools.interactive_view.circuit_get_bus_marker(name=bus, size=10)) 

print(bus_list)

dss_tools.interactive_view.circuit_geoplot(parameter="active power", title="Circuit Plot with Isolated Buses", show=True, bus_markers=bus_list)

[CircuitBusMarker(name='i888888340825002086b', symbol='square', size=10, color='black', marker_name='i888888340825002086b'), CircuitBusMarker(name='82021905002086', symbol='square', size=10, color='black', marker_name='82021905002086'), CircuitBusMarker(name='82031435002086', symbol='square', size=10, color='black', marker_name='82031435002086'), CircuitBusMarker(name='82036215002086', symbol='square', size=10, color='black', marker_name='82036215002086'), CircuitBusMarker(name='82032955002086', symbol='square', size=10, color='black', marker_name='82032955002086'), CircuitBusMarker(name='82033655002086', symbol='square', size=10, color='black', marker_name='82033655002086'), CircuitBusMarker(name='82032275002086', symbol='square', size=10, color='black', marker_name='82032275002086'), CircuitBusMarker(name='82049135002086', symbol='square', size=10, color='black', marker_name='82049135002086'), CircuitBusMarker(name='82050245002086', symbol='square', size=10, color='black', marker_name='82050245002086'), CircuitBusMarker(name='82049695002086', symbol='square', size=10, color='black', marker_name='82049695002086'), CircuitBusMarker(name='82040095002086', symbol='square', size=10, color='black', marker_name='82040095002086'), CircuitBusMarker(name='82049745002086', symbol='square', size=10, color='black', marker_name='82049745002086'), CircuitBusMarker(name='82049895002086', symbol='square', size=10, color='black', marker_name='82049895002086'), CircuitBusMarker(name='82049925002086', symbol='square', size=10, color='black', marker_name='82049925002086'), CircuitBusMarker(name='82040735002086', symbol='square', size=10, color='black', marker_name='82040735002086'), CircuitBusMarker(name='82065615002086', symbol='square', size=10, color='black', marker_name='82065615002086'), CircuitBusMarker(name='82039665002086', symbol='square', size=10, color='black', marker_name='82039665002086'), CircuitBusMarker(name='82042055002086', symbol='square', size=10, color='black', marker_name='82042055002086'), CircuitBusMarker(name='88685565002086', symbol='square', size=10, color='black', marker_name='88685565002086'), CircuitBusMarker(name='88686185002086', symbol='square', size=10, color='black', marker_name='88686185002086'), CircuitBusMarker(name='94074915002086b', symbol='square', size=10, color='black', marker_name='94074915002086b'), CircuitBusMarker(name='94074915002086', symbol='square', size=10, color='black', marker_name='94074915002086'), CircuitBusMarker(name='94125525002086b', symbol='square', size=10, color='black', marker_name='94125525002086b'), CircuitBusMarker(name='94128575002086b', symbol='square', size=10, color='black', marker_name='94128575002086b'), CircuitBusMarker(name='94511165002086b', symbol='square', size=10, color='black', marker_name='94511165002086b'), CircuitBusMarker(name='94511165002086', symbol='square', size=10, color='black', marker_name='94511165002086'), CircuitBusMarker(name='94522045002086', symbol='square', size=10, color='black', marker_name='94522045002086'), CircuitBusMarker(name='94531885002086b', symbol='square', size=10, color='black', marker_name='94531885002086b'), CircuitBusMarker(name='94531885002086', symbol='square', size=10, color='black', marker_name='94531885002086'), CircuitBusMarker(name='94324465002086b', symbol='square', size=10, color='black', marker_name='94324465002086b'), CircuitBusMarker(name='94324465002086', symbol='square', size=10, color='black', marker_name='94324465002086'), CircuitBusMarker(name='94329955002086', symbol='square', size=10, color='black', marker_name='94329955002086'), CircuitBusMarker(name='94329955002086b', symbol='square', size=10, color='black', marker_name='94329955002086b'), CircuitBusMarker(name='94335985002086', symbol='square', size=10, color='black', marker_name='94335985002086'), CircuitBusMarker(name='94335985002086b', symbol='square', size=10, color='black', marker_name='94335985002086b'), CircuitBusMarker(name='94336115002086', symbol='square', size=10, color='black', marker_name='94336115002086'), CircuitBusMarker(name='94336115002086b', symbol='square', size=10, color='black', marker_name='94336115002086b'), CircuitBusMarker(name='94660965002086', symbol='square', size=10, color='black', marker_name='94660965002086'), CircuitBusMarker(name='94661005002086', symbol='square', size=10, color='black', marker_name='94661005002086'), CircuitBusMarker(name='90349985002086', symbol='square', size=10, color='black', marker_name='90349985002086'), CircuitBusMarker(name='95170945002086b', symbol='square', size=10, color='black', marker_name='95170945002086b'), CircuitBusMarker(name='95170975002086b', symbol='square', size=10, color='black', marker_name='95170975002086b'), CircuitBusMarker(name='95200805002086b', symbol='square', size=10, color='black', marker_name='95200805002086b'), CircuitBusMarker(name='95200805002086', symbol='square', size=10, color='black', marker_name='95200805002086'), CircuitBusMarker(name='95217195002086', symbol='square', size=10, color='black', marker_name='95217195002086'), CircuitBusMarker(name='95217195002086b', symbol='square', size=10, color='black', marker_name='95217195002086b'), CircuitBusMarker(name='95224855002086', symbol='square', size=10, color='black', marker_name='95224855002086'), CircuitBusMarker(name='95225005002086', symbol='square', size=10, color='black', marker_name='95225005002086'), CircuitBusMarker(name='94563035002086b', symbol='square', size=10, color='black', marker_name='94563035002086b'), CircuitBusMarker(name='94563035002086', symbol='square', size=10, color='black', marker_name='94563035002086'), CircuitBusMarker(name='95242395002086', symbol='square', size=10, color='black', marker_name='95242395002086'), CircuitBusMarker(name='95244945002086', symbol='square', size=10, color='black', marker_name='95244945002086'), CircuitBusMarker(name='94777925002086b', symbol='square', size=10, color='black', marker_name='94777925002086b'), CircuitBusMarker(name='94777925002086', symbol='square', size=10, color='black', marker_name='94777925002086'), CircuitBusMarker(name='95404055002086b', symbol='square', size=10, color='black', marker_name='95404055002086b'), CircuitBusMarker(name='95404055002086', symbol='square', size=10, color='black', marker_name='95404055002086'), CircuitBusMarker(name='89895775002086b', symbol='square', size=10, color='black', marker_name='89895775002086b'), CircuitBusMarker(name='95423925002086', symbol='square', size=10, color='black', marker_name='95423925002086'), CircuitBusMarker(name='82025135002086', symbol='square', size=10, color='black', marker_name='82025135002086'), CircuitBusMarker(name='91881405002086', symbol='square', size=10, color='black', marker_name='91881405002086'), CircuitBusMarker(name='82051715002086b', symbol='square', size=10, color='black', marker_name='82051715002086b'), CircuitBusMarker(name='96582725002086', symbol='square', size=10, color='black', marker_name='96582725002086'), CircuitBusMarker(name='91881405002086b', symbol='square', size=10, color='black', marker_name='91881405002086b'), CircuitBusMarker(name='88185375002086', symbol='square', size=10, color='black', marker_name='88185375002086'), CircuitBusMarker(name='82049605002086', symbol='square', size=10, color='black', marker_name='82049605002086'), CircuitBusMarker(name='91879905002086b', symbol='square', size=10, color='black', marker_name='91879905002086b'), CircuitBusMarker(name='93304335002086b', symbol='square', size=10, color='black', marker_name='93304335002086b'), CircuitBusMarker(name='81463935002086', symbol='square', size=10, color='black', marker_name='81463935002086'), CircuitBusMarker(name='i888888467345002086', symbol='square', size=10, color='black', marker_name='i888888467345002086'), CircuitBusMarker(name='i888888340595002086', symbol='square', size=10, color='black', marker_name='i888888340595002086'), CircuitBusMarker(name='93304305002086', symbol='square', size=10, color='black', marker_name='93304305002086'), CircuitBusMarker(name='82032055002086', symbol='square', size=10, color='black', marker_name='82032055002086'), CircuitBusMarker(name='81480555002086b', symbol='square', size=10, color='black', marker_name='81480555002086b'), CircuitBusMarker(name='96957955002086b', symbol='square', size=10, color='black', marker_name='96957955002086b'), CircuitBusMarker(name='i888888516525002086g', symbol='square', size=10, color='black', marker_name='i888888516525002086g'), CircuitBusMarker(name='int157715002086', symbol='square', size=10, color='black', marker_name='int157715002086'), CircuitBusMarker(name='i888888516585002086', symbol='square', size=10, color='black', marker_name='i888888516585002086')]