Preparação OpenDSS

In [52]:
from py_dss_toolkit import dss_tools
import py_dss_interface

dss = py_dss_interface.DSS()

dss_tools.update_dss(dss)

dss_file = r"C:\Dados_teste\OpenDSS\GWO\Alim_Meia_Ponte_5_REDUZIDO\Master_PyDSS_Interface.dss"

dss.text(f"compile [{dss_file}]")

dss.text("Redirect 'PV_System_120_MeiaPonte.dss'")
dss.text("buscoords buscoords.csv")

pvsystems_df = dss_tools.model.pvsystems_df
buses_df = dss_tools.model.buses_df

display(pvsystems_df)

bus_list = pvsystems_df["bus1"].apply(lambda x: x.split(".")[0]).tolist()
display(buses_df)

       name phases                    bus1    kv  ... spectrum basefreq enabled like
0      pv_1      3  82036275286964.1.2.3.4  0.38  ...                60    true
1      pv_2      3  82036275286964.1.2.3.4  0.38  ...                60    true
2      pv_3      3  82026915286812.1.2.3.4  0.38  ...                60    true
3      pv_4      3  82026915286812.1.2.3.4  0.38  ...                60    true
4      pv_5      3  82032765552819.1.2.3.4  0.38  ...                60    true
..      ...    ...                     ...   ...  ...      ...      ...     ...  ...
115  pv_116      3  82056385286891.1.2.3.4  0.38  ...                60    true
116  pv_117      3  82064145286858.1.2.3.4  0.38  ...                60    true
117  pv_118      3  82064145286858.1.2.3.4  0.38  ...                60    true
118  pv_119      3  82040015286941.1.2.3.4  0.38  ...                60    true
119  pv_120      3  82040015286941.1.2.3.4  0.38  ...                60    true

[120 rows x 55 columns]

                 name         nodes  ...  section_id  total_customers
0      84808465002086     [1, 2, 3]  ...           0                0
1      81463945002086     [1, 2, 3]  ...           0                0
2     81463945002086b     [1, 2, 3]  ...           0                0
3      82034695002086     [1, 2, 3]  ...           0                0
4     82034695002086b     [1, 2, 3]  ...           0                0
...               ...           ...  ...         ...              ...
1212   85167275333902  [1, 2, 3, 4]  ...           0                0
1213   82056945740255  [1, 2, 3, 4]  ...           0                0
1214   96033635740270  [1, 2, 3, 4]  ...           0                0
1215   96264655744153  [1, 2, 3, 4]  ...           0                0
1216   81481405444435  [1, 2, 3, 4]  ...           0                0

[1217 rows x 17 columns]

Verificando se há alguma barra de carga fora do Buses_df

In [61]:
count = 0
print(bus_list)
for bus in bus_list:
    if buses_df.query(f"name == '{bus}'").empty:
        count += 1

print(count)

buses_df.query("name == '82036275286964'")

['82036275286964', '82036275286964', '82026915286812', '82026915286812', '82032765552819', '82032765552819', '82025745286821', '82025745286821', '82049885286934', '82049885286934', '82023395286788', '82023395286788', '82049545286931', '82049545286931', '82028035286810', '82028035286810', '82054305286917', '82054305286917', '82020175286794', '82020175286794', '97400945286961', '97400945286961', '82037555286840', '82037555286840', '82027735286815', '82027735286815', '82027905286808', '82027905286808', '82031445286959', '82031445286959', '90855665286807', '90855665286807', '82053975286918', '82053975286918', '82027135286819', '82027135286819', '82027655286814', '82027655286814', '82062475286857', '82062475286857', '82038095286834', '82038095286834', '82021995286799', '82021995286799', '82036745286803', '82036745286803', '82026685286811', '82026685286811', '82022605286791', '82022605286791', '82034555505307', '82034555505307', '82029355286816', '82029355286816', '82035485286965', '82035485286965', '82033055286804', '82033055286804', '82031405286958', '82031405286958', '81460505286830', '81460505286830', '82049805286933', '82049805286933', '82024325286800', '82024325286800', '82054235286916', '82054235286916', '82020405286795', '82020405286795', '82038115286835', '82038115286835', '82022455286790', '82022455286790', '82036045286966', '82036045286966', '82038825286839', '82038825286839', '82063385286866', '82063385286866', '82033945286960', '82033945286960', '82041995286833', '82041995286833', '82065285286862', '82065285286862', '82023305286787', '82023305286787', '82019965286792', '82019965286792', '82053635286914', '82053635286914', '82024965286806', '82024965286806', '82028045286809', '82028045286809', '82050465286938', '82050465286938', '82044385286867', '82044385286867', '82039695286842', '82039695286842', '82042655286828', '82042655286828', '82043025286831', '82043025286831', '82042275286845', '82042275286845', '82040415286945', '82040415286945', '82044325557353', '82044325557353', '82056915286890', '82056915286890', '82056385286891', '82056385286891', '82064145286858', '82064145286858', '82040015286941', '82040015286941']
0

                name         nodes  ...  section_id  total_customers
1201  82036275286964  [1, 2, 3, 4]  ...           0                0

[1 rows x 17 columns]

Código PVLIB Python

In [59]:
import pvlib

bus_list_df = buses_df[buses_df["name"].isin(bus_list)]

coordinates = []
for _, row in bus_list_df.iterrows():
    coord = (row["x"], row["y"])
    coordinates.append(coord)

start_year = 2019
end_year = 2023

period = end_year-start_year+1
irrad = []
t = 1
for location in coordinates:
    longitude, latitude = location
    data = pvlib.iotools.get_pvgis_hourly(latitude, longitude, start=start_year, end=end_year, components=False,timeout=300)[0]
    print('Baixou %i' % t, end = '\r')
    t+=1
    irrad.append(data)

Diretório de Trabalho

In [ ]:
import os

print(os.getcwd())

C:\Dados_teste\OpenDSS\GWO

Organização dos Dados

In [75]:
import pandas as pd

index_time = pd.date_range('2010-01-01', '2011-01-01', freq='1h', inclusive='left')
new_index=[]
for i in index_time:
    time = i.strftime('%d-%m %H:%M:%S')
    new_index.append(time)

all_hourly_means = []
h=1
for i in irrad:
    df_5year = pd.DataFrame()
    
    df_5year['2019'] = i.iloc[0:8760]["poa_global"].values
    df_5year['2020'] = pd.concat([i.iloc[8760:10176]["poa_global"], i.iloc[10200:17544]["poa_global"]]).values #Remove o dia extra do ano bissexto
    df_5year['2021'] = i.iloc[17544:26304]["poa_global"].values
    df_5year['2022'] = i.iloc[26304:35064]["poa_global"].values
    df_5year['2023'] = i.iloc[35064:43824]["poa_global"].values
       
    df_5year['mean'] = df_5year.mean(axis=1)
    df_5year.index = new_index
    df_5year.to_csv('./irrad_points/point-%i.csv' % h)
    h+=1
    df_5year.index = pd.date_range('2010-01-01', '2011-01-01', freq='1h', inclusive='left')
    df_5year['hour'] = df_5year.index.hour
    
    hourly_means = df_5year.groupby('hour')['mean'].mean()
    
    all_hourly_means.append(hourly_means)

Salvando os dados de irradiância

In [76]:
five_year = []
for t in range(60):
    df = pd.read_csv('./irrad_points/point-%i.csv' % (t+1), index_col=0)
    five_year.append(df)

Criação do DataFrame (salvo em CSV)

In [78]:
hourly_means_df = pd.DataFrame(all_hourly_means)
for hour in range(24):
    col_name = f'irrad_{hour}h'
    bus_list_df[col_name] = hourly_means_df.iloc[:, hour].values

display(bus_list_df)
bus_list_df.to_csv("./irrad_points/buses_with_irradiance.csv")

                name         nodes  num_nodes  ...  irrad_21h  irrad_22h  irrad_23h
1078  82023305286787  [1, 2, 3, 4]          4  ...  11.893025        0.0        0.0
1079  82023395286788  [1, 2, 3, 4]          4  ...  11.779781        0.0        0.0
1081  82022455286790  [1, 2, 3, 4]          4  ...  11.893392        0.0        0.0
1082  82022605286791  [1, 2, 3, 4]          4  ...  11.900668        0.0        0.0
1083  82019965286792  [1, 2, 3, 4]          4  ...  11.893019        0.0        0.0
1085  82020175286794  [1, 2, 3, 4]          4  ...  11.890855        0.0        0.0
1086  82020405286795  [1, 2, 3, 4]          4  ...  11.893458        0.0        0.0
1090  82021995286799  [1, 2, 3, 4]          4  ...  11.874838        0.0        0.0
1091  82024325286800  [1, 2, 3, 4]          4  ...  11.900756        0.0        0.0
1094  82036745286803  [1, 2, 3, 4]          4  ...  11.908932        0.0        0.0
1095  82033055286804  [1, 2, 3, 4]          4  ...  11.909068        0.0        0.0
1097  82024965286806  [1, 2, 3, 4]          4  ...  11.909068        0.0        0.0
1098  90855665286807  [1, 2, 3, 4]          4  ...  11.909047        0.0        0.0
1099  82027905286808  [1, 2, 3, 4]          4  ...  11.909025        0.0        0.0
1100  82028045286809  [1, 2, 3, 4]          4  ...  11.908986        0.0        0.0
1101  82028035286810  [1, 2, 3, 4]          4  ...  11.909003        0.0        0.0
1102  82026685286811  [1, 2, 3, 4]          4  ...  11.909101        0.0        0.0
1103  82026915286812  [1, 2, 3, 4]          4  ...  11.909112        0.0        0.0
1105  82027655286814  [1, 2, 3, 4]          4  ...  11.902225        0.0        0.0
1106  82027735286815  [1, 2, 3, 4]          4  ...  11.909107        0.0        0.0
1107  82029355286816  [1, 2, 3, 4]          4  ...  11.909079        0.0        0.0
1110  82027135286819  [1, 2, 3, 4]          4  ...  11.909112        0.0        0.0
1112  82025745286821  [1, 2, 3, 4]          4  ...  11.909101        0.0        0.0
1113  82042655286828  [1, 2, 3, 4]          4  ...  11.763101        0.0        0.0
1115  81460505286830  [1, 2, 3, 4]          4  ...  11.779775        0.0        0.0
1116  82043025286831  [1, 2, 3, 4]          4  ...  11.891660        0.0        0.0
1118  82041995286833  [1, 2, 3, 4]          4  ...  11.873332        0.0        0.0
1119  82038095286834  [1, 2, 3, 4]          4  ...  11.890762        0.0        0.0
1120  82038115286835  [1, 2, 3, 4]          4  ...  11.892926        0.0        0.0
1124  82038825286839  [1, 2, 3, 4]          4  ...  11.880214        0.0        0.0
1125  82037555286840  [1, 2, 3, 4]          4  ...  11.890800        0.0        0.0
1127  82039695286842  [1, 2, 3, 4]          4  ...  11.551233        0.0        0.0
1130  82042275286845  [1, 2, 3, 4]          4  ...  11.873321        0.0        0.0
1132  82062475286857  [1, 2, 3, 4]          4  ...  11.909079        0.0        0.0
1133  82064145286858  [1, 2, 3, 4]          4  ...  11.879436        0.0        0.0
1136  82065285286862  [1, 2, 3, 4]          4  ...  11.908877        0.0        0.0
1140  82063385286866  [1, 2, 3, 4]          4  ...  11.908805        0.0        0.0
1141  82044385286867  [1, 2, 3, 4]          4  ...  11.908926        0.0        0.0
1144  82056915286890  [1, 2, 3, 4]          4  ...  11.909030        0.0        0.0
1145  82056385286891  [1, 2, 3, 4]          4  ...  11.909003        0.0        0.0
1146  82053635286914  [1, 2, 3, 4]          4  ...  11.909036        0.0        0.0
1148  82054235286916  [1, 2, 3, 4]          4  ...  11.909036        0.0        0.0
1149  82054305286917  [1, 2, 3, 4]          4  ...  11.909019        0.0        0.0
1150  82053975286918  [1, 2, 3, 4]          4  ...  11.909036        0.0        0.0
1153  82049545286931  [1, 2, 3, 4]          4  ...  11.909052        0.0        0.0
1155  82049805286933  [1, 2, 3, 4]          4  ...  11.909036        0.0        0.0
1156  82049885286934  [1, 2, 3, 4]          4  ...  11.909063        0.0        0.0
1160  82050465286938  [1, 2, 3, 4]          4  ...  11.909036        0.0        0.0
1163  82040015286941  [1, 2, 3, 4]          4  ...  11.908997        0.0        0.0
1167  82040415286945  [1, 2, 3, 4]          4  ...  11.900351        0.0        0.0
1178  82034555505307  [1, 2, 3, 4]          4  ...  11.908953        0.0        0.0
1186  82032765552819  [1, 2, 3, 4]          4  ...  11.908975        0.0        0.0
1189  82044325557353  [1, 2, 3, 4]          4  ...  11.908926        0.0        0.0
1195  82031405286958  [1, 2, 3, 4]          4  ...  11.909003        0.0        0.0
1196  82031445286959  [1, 2, 3, 4]          4  ...  11.909025        0.0        0.0
1197  82033945286960  [1, 2, 3, 4]          4  ...  11.908953        0.0        0.0
1198  97400945286961  [1, 2, 3, 4]          4  ...  11.908959        0.0        0.0
1201  82036275286964  [1, 2, 3, 4]          4  ...  11.908953        0.0        0.0
1202  82035485286965  [1, 2, 3, 4]          4  ...  11.908953        0.0        0.0
1203  82036045286966  [1, 2, 3, 4]          4  ...  11.908959        0.0        0.0

[60 rows x 41 columns]

Testes com o DataFrame dos Grafos

In [29]:
graph_df = dss_tools.model.graph_df
buses_df = dss_tools.model.buses_df
count_bus12, count_bus21, count_bus_equal = 0, 0, 0

for _, row in graph_df.iterrows():
    bus1 = row["bus1"]
    bus2 = row["bus2"]

    distance_1 = buses_df.query(f"name == '{bus1}'")["distance"].iloc[0]
    distance_2 = buses_df.query(f"name == '{bus2}'")["distance"].iloc[0]

    if distance_1 > distance_2:
        count_bus12 += 1

    elif distance_1 < distance_2:
        count_bus21 += 1

    elif distance_1 == distance_2:
        count_bus_equal += 1
        print(f"Bus1: {row["bus1"]}, Bus2: {row["bus2"]}")


        

print("Contagem de grafos com bus1 mais distante que bus2: ", count_bus12)
print("Contagem de grafos com bus1 mais próximo que bus2: ", count_bus21)
print("Contagem de grafos com bus1 igualmente distante do source em relação a bus2: ", count_bus_equal)
print("Total: ", len(graph_df))

Bus1: 84808465002086, Bus2: i888888516545002086
Bus1: 84808465002086, Bus2: i888888340825002086
Bus1: i888888516565002086b, Bus2: i888888516565002086
Bus1: i888888516565002086, Bus2: i888888516575002086b
Bus1: i888888516575002086b, Bus2: i888888516575002086
Bus1: i888888516575002086, Bus2: int157715002086
Bus1: i888888516555002086b, Bus2: i888888516555002086
Bus1: i888888516555002086, Bus2: i888888516565002086b
Bus1: i888888516555002086, Bus2: i888888516585002086
Bus1: i888888340825002086, Bus2: i888888340595002086
Bus1: i888888340825002086, Bus2: i888888340855002086
Bus1: i888888340825002086, Bus2: i888888340825002086b
Bus1: 82021885002086, Bus2: 82021885286798
Bus1: 82021995002086, Bus2: 82021995286799
Bus1: 82022225002086, Bus2: 82022225286801
Bus1: 82024125002086, Bus2: 82024125552309
Bus1: 82024325002086, Bus2: 82024325286800
Bus1: 82019965002086, Bus2: 82019965286792
Bus1: 82020055002086, Bus2: 82020055286793
Bus1: 82020175002086, Bus2: 82020175286794
Bus1: 82020405002086, Bus2: 82020405286795
Bus1: 82020555002086, Bus2: 82020555286796
Bus1: 82020675002086, Bus2: 82020675286797
Bus1: 82025745002086, Bus2: 82025745286821
Bus1: 82026685002086, Bus2: 82026685286811
Bus1: 82026915002086, Bus2: 82026915286812
Bus1: 82028365002086, Bus2: 82028365286813
Bus1: 82027655002086, Bus2: 82027655286814
Bus1: 82027735002086, Bus2: 82027735286815
Bus1: 82027135002086, Bus2: 82027135286819
Bus1: 82026625002086, Bus2: 82026625286820
Bus1: 82029275002086, Bus2: 82029275286817
Bus1: 82026575002086, Bus2: 82026575502834
Bus1: 82028855002086, Bus2: 82028855286818
Bus1: 82029355002086, Bus2: 82029355286816
Bus1: 82029725002086, Bus2: 82029725286967
Bus1: 82036745002086, Bus2: 82036745286803
Bus1: 82033055002086, Bus2: 82033055286804
Bus1: 82035255002086, Bus2: 82035255286963
Bus1: 82036275002086, Bus2: 82036275286964
Bus1: 82035485002086, Bus2: 82035485286965
Bus1: 82031405002086, Bus2: 82031405286958
Bus1: 82031445002086, Bus2: 82031445286959
Bus1: 82036045002086, Bus2: 82036045286966
Bus1: 82033395002086, Bus2: 82033395286805
Bus1: 82034125002086, Bus2: 82034125470133
Bus1: 82024965002086, Bus2: 82024965286806
Bus1: 82027905002086, Bus2: 82027905286808
Bus1: 82028035002086, Bus2: 82028035286810
Bus1: 82028045002086, Bus2: 82028045286809
Bus1: 97400945002086, Bus2: 97400945286961
Bus1: 82034385002086, Bus2: 82034385713817
Bus1: 82034445002086, Bus2: 82034445286962
Bus1: 82021615002086, Bus2: 82021615286802
Bus1: 82022295002086, Bus2: 82022295286789
Bus1: 82022455002086, Bus2: 82022455286790
Bus1: 82022605002086, Bus2: 82022605286791
Bus1: 82023305002086, Bus2: 82023305286787
Bus1: 82023395002086, Bus2: 82023395286788
Bus1: 82034835002086, Bus2: 82034835286707
Bus1: 81460535002086, Bus2: 81460535479360
Bus1: 81460505002086, Bus2: 81460505286830
Bus1: 82038825002086, Bus2: 82038825286839
Bus1: 82055725002086, Bus2: 82055725286871
Bus1: 82062715002086, Bus2: 82062715499009
Bus1: 82062475002086, Bus2: 82062475286857
Bus1: 82055955002086, Bus2: 82055955569878
Bus1: 82056385002086, Bus2: 82056385286891
Bus1: 82049375002086, Bus2: 82049375286930
Bus1: 82056915002086, Bus2: 82056915286890
Bus1: 85167275002086, Bus2: 85167275333902
Bus1: 82063385002086, Bus2: 82063385286866
Bus1: 82039725002086, Bus2: 82039725286944
Bus1: 82039815002086, Bus2: 82039815286939
Bus1: 82049545002086, Bus2: 82049545286931
Bus1: 82064065002086, Bus2: 82064065286861
Bus1: 82064145002086, Bus2: 82064145286858
Bus1: 82064825002086, Bus2: 82064825286863
Bus1: 82039945002086, Bus2: 82039945286940
Bus1: 82040015002086, Bus2: 82040015286941
Bus1: 82040165002086, Bus2: 82040165286942
Bus1: 82049765002086, Bus2: 82049765286932
Bus1: 82049805002086, Bus2: 82049805286933
Bus1: 82049885002086, Bus2: 82049885286934
Bus1: 82050325002086, Bus2: 82050325286935
Bus1: 82064425002086, Bus2: 82064425286864
Bus1: 82065005002086, Bus2: 82065005286865
Bus1: 82040265002086, Bus2: 82040265286943
Bus1: 82040415002086, Bus2: 82040415286945
Bus1: 82040575002086, Bus2: 82040575286946
Bus1: 82049975002086, Bus2: 82049975286936
Bus1: 82050035002086, Bus2: 82050035286937
Bus1: 82050465002086, Bus2: 82050465286938
Bus1: 82040855002086, Bus2: 82040855286947
Bus1: 82065235002086, Bus2: 82065235286860
Bus1: 82065285002086, Bus2: 82065285286862
Bus1: 82044325002086, Bus2: 82044325557353
Bus1: 82044385002086, Bus2: 82044385286867
Bus1: 90190165002086, Bus2: 90190165552038
Bus1: 82060535002086, Bus2: 82060535286919
Bus1: 82061675002086, Bus2: 82061675551754
Bus1: 82053635002086, Bus2: 82053635286914
Bus1: 82053975002086, Bus2: 82053975286918
Bus1: 82054535002086, Bus2: 82054535286915
Bus1: 82054825002086, Bus2: 82054825286872
Bus1: 82053655002086, Bus2: 82053655286718
Bus1: 89701935002086, Bus2: 89701935535535
Bus1: 82054155002086, Bus2: 82054155688575
Bus1: 82054235002086, Bus2: 82054235286916
Bus1: 82054305002086, Bus2: 82054305286917
Bus1: 82038095002086, Bus2: 82038095286834
Bus1: 82038115002086, Bus2: 82038115286835
Bus1: 82041105002086, Bus2: 82041105286836
Bus1: 82041215002086, Bus2: 82041215286837
Bus1: 82039455002086, Bus2: 82039455286841
Bus1: 82039695002086, Bus2: 82039695286842
Bus1: 82042105002086, Bus2: 82042105286843
Bus1: 82042165002086, Bus2: 82042165286844
Bus1: 82042275002086, Bus2: 82042275286845
Bus1: 82041545002086, Bus2: 82041545286846
Bus1: 82043025002086, Bus2: 82043025286831
Bus1: 82042575002086, Bus2: 82042575286832
Bus1: 82042655002086, Bus2: 82042655286828
Bus1: 82041905002086, Bus2: 82041905286838
Bus1: 82037555002086, Bus2: 82037555286840
Bus1: 82032765002086, Bus2: 82032765552819
Bus1: 93945325002086, Bus2: 93945325675373
Bus1: 88287355002086, Bus2: 88287355491509
Bus1: 82033945002086, Bus2: 82033945286960
Bus1: 82034555002086, Bus2: 82034555505307
Bus1: 84503635002086, Bus2: 84503635323939
Bus1: 90305705002086, Bus2: 90305705555964
Bus1: 90349975002086, Bus2: 90349975558213
Bus1: 89813615002086, Bus2: 89813615537656
Bus1: 90017935002086, Bus2: 90017935702287
Bus1: 90017985002086, Bus2: 90017985547722
Bus1: 90409505002086, Bus2: 90409505560489
Bus1: 90214315002086, Bus2: 90214315552553
Bus1: 95141555002086, Bus2: 95141555719448
Bus1: 81481405002086, Bus2: 81481405444435
Bus1: 90855665002086, Bus2: 90855665286807
Bus1: 82031945002086, Bus2: 82031945574596
Bus1: 81479715002086, Bus2: 81479715440862
Bus1: 82056945002086, Bus2: 82056945740255
Bus1: 96033635002086, Bus2: 96033635740270
Bus1: 90938795002086, Bus2: 90938795577671
Bus1: 82041995002086, Bus2: 82041995286833
Bus1: 81490995002086, Bus2: 81490995286829
Bus1: 96264655002086, Bus2: 96264655744153
Bus1: 93119985002086, Bus2: 93119985647498
Bus1: 88109845002086, Bus2: 88109845485359
Bus1: i888888340885002086, Bus2: i888888467345002086
Bus1: i888888340855002086, Bus2: i888888340885002086
Bus1: 82032105002086, Bus2: 82032105469845
Bus1: 87774405002086, Bus2: 87774405472282
Bus1: i888888516535002086, Bus2: i888888516525002086g
Bus1: i888888516545002086, Bus2: i888888516535002086
Bus1: i888888516545002086, Bus2: i888888516555002086b
Bus1: mrt_82034475002086trf_5286699a, Bus2: 82034475286699
Bus1: mrt_82034845002086trf_5286708a, Bus2: 82034845286708
Contagem de grafos com bus1 mais distante que bus2:  0
Contagem de grafos com bus1 mais próximo que bus2:  1056
Contagem de grafos com bus1 igualmente distante do source em relação a bus2:  160
Total:  1216

In [34]:
display(graph_df.query("bus1 == '82021885002086' and bus2 == '82021885286798'"))

display(buses_df.query("name == '82021885002086' or name == '82021885286798'"))

               bus1            bus2  ... kv_tertiary conn_tertiary
145  82021885002086  82021885286798  ...         NaN           NaN

[1 rows x 20 columns]

                name         nodes  ...  section_id  total_customers
132   82021885002086     [1, 2, 3]  ...           0                0
1089  82021885286798  [1, 2, 3, 4]  ...           0                0

[2 rows x 17 columns]

Testes Violação Térmica

In [43]:
from py_dss_toolkit import dss_tools
import py_dss_interface

dss = py_dss_interface.DSS()

dss_tools.update_dss(dss)

dss_file = r"C:\Dados_teste\OpenDSS\GWO\Alim_Meia_Ponte_5_REDUZIDO\Master_PyDSS_Interface.dss"

dss.text(f"compile [{dss_file}]")

dss.text("Redirect 'PV_System_120_MeiaPonte.dss'")
dss.text("buscoords buscoords.csv")
dss.text("New monitor.smt_53074062 element=line.smt_53074062 mode=0 terminal=1")
dss.text("New monitor.smt_53072887 element=line.smt_53072887 mode=0 terminal=1")
dss.text("New monitor.smt_53073562 element=line.smt_53073562 mode=0 terminal=1")

dss_tools.simulation.solve_daily(stepsize="1h", number=24)

In [ ]:
dss_tools.results.set_violation_current_limit_type(limit_type="emerg_amps")
dss_tools.results.set_currents_loading_threshold_percent(threshold_percent=20)  #Se a corrente atingir 20% do limite, ele aponta como anormal
dss_tools.interactive_view.circuit_plot(parameter="thermal violations")

#Com Emerg Amps = 600 A, todas as linhas com corrente acima de 120 A na última hora aparecem na lista

In [ ]:
lines_df = dss_tools.model.lines_df
df_monitor_line_abnormal = dss_tools.results.monitor("smt_53074062")
df_monitor_line_normal = dss_tools.results.monitor("smt_53072887")
df_monitor_line_both = dss_tools.results.monitor("smt_53073562")

print("Anormal\n")
display(df_monitor_line_abnormal[[" I1", " I2", " I3"]])

print("Normal\n")
display(df_monitor_line_normal[[" I1", " I2", " I3"]])

print("Anormal em 10% e Normal em 20%\n")
display(df_monitor_line_both[[" I1", " I2", " I3"]])

display(lines_df.query("name == 'smt_53074062' or name == 'smt_53072887' or name == 'smt_53073562'"))

Anormal

            I1          I2          I3
0   212.502686  212.537857  212.501923
1   193.656952  193.689468  193.656296
2   180.577164  180.607849  180.576599
3   177.884705  177.914993  177.884140
4   176.119507  176.149551  176.118958
5   166.580856  166.611847  166.580215
6   107.236641  107.265701  107.235588
7   102.223915  102.211769  102.223030
8   182.261093  182.238419  182.260590
9   236.486954  236.461548  236.486496
10  262.089264  262.062836  262.088837
11  247.753571  247.727570  247.752884
12  199.593964  199.572128  199.592712
13  157.118790  157.102005  157.117401
14  112.626671  112.630310  112.624542
15  116.565605  116.595512  116.563629
16  200.373108  200.413925  200.371841
17  274.007629  274.051300  274.006500
18  327.274750  327.325256  327.272980
19  337.636414  337.688202  337.634491
20  330.705505  330.756378  330.703644
21  311.563965  311.612579  311.562469
22  275.049652  275.093475  275.048523
23  248.801865  248.842087  248.800888

Normal

          I1        I2        I3
0   1.369439  1.369429  1.369435
1   1.247800  1.247792  1.247796
2   1.163393  1.163386  1.163390
3   1.146013  1.146006  1.146009
4   1.134624  1.134617  1.134620
5   1.186676  1.186668  1.186672
6   1.270785  1.270777  1.270781
7   1.240013  1.240005  1.240010
8   1.322037  1.322028  1.322033
9   1.455375  1.455364  1.455370
10  1.496248  1.496236  1.496243
11  1.621460  1.621447  1.621455
12  1.725257  1.725242  1.725251
13  1.630893  1.630879  1.630887
14  1.661377  1.661363  1.661371
15  1.635660  1.635646  1.635654
16  1.673413  1.673398  1.673407
17  1.766486  1.766470  1.766479
18  2.109635  2.109612  2.109626
19  2.177146  2.177121  2.177136
20  2.131534  2.131510  2.131524
21  2.008519  2.008498  2.008511
22  1.773181  1.773164  1.773174
23  1.603730  1.603717  1.603724

Ambos

           I1         I2         I3
0   52.524269  52.523026  52.524075
1   47.871204  47.870033  47.871037
2   44.641121  44.639996  44.640976
3   43.976418  43.975300  43.976273
4   43.540413  43.539303  43.540268
5   41.275784  41.274567  41.275620
6   26.913109  26.911282  26.912846
7   24.450102  24.448364  24.449875
8   43.387299  43.386253  43.387169
9   56.373882  56.372978  56.373764
10  62.493748  62.492901  62.493641
11  59.144737  59.143784  59.144562
12  47.767197  47.765926  47.766876
13  37.688236  37.686699  37.687885
14  27.540594  27.538303  27.540058
15  29.185297  29.182968  29.184811
16  49.758060  49.756386  49.757740
17  67.706894  67.705391  67.706604
18  80.904327  80.902344  80.903778
19  83.453835  83.451683  83.453178
20  81.804298  81.802193  81.803658
21  76.974266  76.972504  76.973862
22  67.965538  67.964027  67.965248
23  61.486561  61.485172  61.486309

             name                  bus1  ... enabled like
340  smt_53072887  82022605002086.1.2.3  ...    true
624  smt_53073562  82060845002086.1.2.3  ...    true
996  smt_53074062  81490895002086.1.2.3  ...    true

[3 rows x 43 columns]